[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs= 200
via_ir = true
remappings = [
      "@uniswap/v3-core/=lib/v3-core/",
      "v3-periphery/=lib/v3-periphery/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
